CREATE TABLE [dbo].[Comment]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Content] VARCHAR (1000) NOT NULL,
	[Date] DATE NOT NULL,
	[UserId] INT NOT NULL,
	[TicketId] INT NOT NULL,
	FOREIGN KEY (TicketId) REFERENCES Ticket(Id) ON DELETE CASCADE,
	FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
)
